Update download_and_installation.rst
I got following error when install MAVProxy without pathlib.
--
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.4 requires pathlib, which is not installed.
--
This error is cleared with installing pathlib.